# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ygg < Formula
  desc "Simple CLI for managing git worktrees"
  homepage "https://github.com/joch/ygg"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joch/ygg/releases/download/v0.4.0/ygg_0.4.0_Darwin_x86_64.tar.gz"
      sha256 "fbb80e375f6639766c2b9a8c833d05d20915be37596c77c04ab6e79420ae60fa"

      define_method(:install) do
        bin.install "ygg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joch/ygg/releases/download/v0.4.0/ygg_0.4.0_Darwin_arm64.tar.gz"
      sha256 "d6686f78116f3d854fd52b35dbea08e755d42083aaabbdc0ea5a26fe6b239c7e"

      define_method(:install) do
        bin.install "ygg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/joch/ygg/releases/download/v0.4.0/ygg_0.4.0_Linux_x86_64.tar.gz"
      sha256 "1ae23eac23ec1836a49ed39e190787804a2c28624be674c9d718453965506599"
      define_method(:install) do
        bin.install "ygg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joch/ygg/releases/download/v0.4.0/ygg_0.4.0_Linux_arm64.tar.gz"
      sha256 "8f0771f09736ea7a982062392aeb2e0a3832e79b36afe48071ee77d312fc9132"
      define_method(:install) do
        bin.install "ygg"
      end
    end
  end

  test do
    system "#{bin}/ygg", "--version"
  end
end
