# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ygg < Formula
  desc "Simple CLI for managing git worktrees"
  homepage "https://github.com/joch/ygg"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joch/ygg/releases/download/v0.5.0/ygg_0.5.0_Darwin_x86_64.tar.gz"
      sha256 "feb42b119393acb9261015c468e2172699d4a02a39d0c52e94d20e105814125f"

      define_method(:install) do
        bin.install "ygg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joch/ygg/releases/download/v0.5.0/ygg_0.5.0_Darwin_arm64.tar.gz"
      sha256 "42b7e15162d5875fd1c8457fc8215b2f05c0622f90c1d9324cf1adf67bcb6cc9"

      define_method(:install) do
        bin.install "ygg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/joch/ygg/releases/download/v0.5.0/ygg_0.5.0_Linux_x86_64.tar.gz"
      sha256 "02f0cabe3af888fb8b79da557978ed3d6cac8a8813bcd817a6f928c7481070c8"
      define_method(:install) do
        bin.install "ygg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joch/ygg/releases/download/v0.5.0/ygg_0.5.0_Linux_arm64.tar.gz"
      sha256 "6ff0ae7babdc40f9c16d9980b0132754a0fc9e04820a75b14c746f10c30417ff"
      define_method(:install) do
        bin.install "ygg"
      end
    end
  end

  test do
    system "#{bin}/ygg", "--version"
  end
end
